---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-image
  commands:
  - docker build --no-cache -t webapp-test:staging -f Dockerfile-staging .

trigger:
  branch:
  - staging
