---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-image
  commands:
  - docker build --no-cache -t webapp-test:staging -f Dockerfile-staging .
  - docker stack deploy -c stack-staging.yml drone-test

trigger:
  branch:
  - staging
