stages:
  - setup
  - install_dependencies
  - build
  - dockerize
  - swarmit

prepare:
  stage: setup
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
  script:
    - npm install

install_dependencies:
  stage: install_dependencies
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
  tags:
    - webapp
  only:
    - staging
  script:
    - npm ci
  only:
    changes:
      - package-lock.json

build:
  stage: build
  tags:
    - webapp
  only:
    - staging
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run build:stage
  artifacts:
    paths:
      - build

dockerize:
  environment: staging
  stage: dockerize
  tags:
    - webapp
  only:
    - staging
  script:
    - docker build -t dplk-webapp -f Dockerfile-staging .

swarmit:
  environment: staging
  stage: swarmit
  tags:
    - webapp
  only:
    - staging
  script:
    - docker stack deploy -c docker-compose.yml dplk-webapp
