stages:
  - install_dependencies
  - build
  - dockerize
  - swarmit

install_dependencies:
  stage: install_dependencies
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
  tags:
    - webapp
  only:
    - staging
  script:
    - npm install

build:
  stage: build
  tags:
    - webapp
  only:
    - staging
  cache: 
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run build:stage
  artifacts:
    paths:
      - dist

dockerize:
  environment: staging
  stage: dockerize
  tags:
    - webapp
  only:
    - staging
  script:
    - docker build -t dplk-webapp -f Dockerfile-staging .
  dependencies:
    - build

swarmit:
  environment: staging
  stage: swarmit
  tags:
    - webapp
  only:
    - staging
  script:
    - docker stack deploy -c docker-compose.yml dplk-webapp
