version: '3.7'

services:

  dplk-webapp:
    image: dplk-webapp
    ports:
      - '8002:80'
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == pensiuncore


