# build environment
FROM node:12.10.0 as build

WORKDIR /app
ADD . /app

RUN npm install
RUN npm run build:stage

# production environment
FROM nginx:1.16.0-alpine

COPY --from=build /app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 8002

CMD ["nginx", "-g", "daemon off;"]