# build environment
FROM node:latest as build

WORKDIR /app
ADD . /app

RUN npm install
RUN npm run build:prod

# production environment
FROM nginx:1.16.0-alpine

COPY --from=build /app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginxprod/nginx.conf /etc/nginx/conf.d

EXPOSE 8003

CMD ["nginx", "-g", "daemon off;"]