FROM nginx:1.16.0-alpine

WORKDIR /app
ADD dist /app

COPY /app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 8002

CMD ["nginx", "-g", "daemon off;"]